[package]
name = "blake-hash"
version = "0.3.2"
authors = ["The CryptoCorrosion Contributors"]
license = "MIT/Apache-2.0"
description = "BLAKE hash functions"
repository = "https://github.com/cryptocorrosion/cryptocorrosion"
keywords = ["crypto", "blake", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
block-buffer = { git = "https://github.com/mesalock-linux/rustcrypto-utils-sgx" }
digest = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
lazy_static = { version = "1.2", features = ["spin_no_std"], optional = true }
simd = { package = "ppv-lite86", git = "https://github.com/mesalock-linux/cryptocorrosion-sgx", version = "0.2.0", optional = true }

[features]
default = ["simd", "std"]
std = []

[dev-dependencies]
#digest = { version = "0.8", features = ["dev"] }

[badges]
travis-ci = { repository = "cryptocorrosion/cryptocorrosion" }
